# Generated by Django 2.2.1 on 2019-06-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190619_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
